/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dictionary;

/**
 *
 * 
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.awt.Color;
import java.awt.TextField;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.JTextField;


public class dictionaryr extends javax.swing.JFrame implements ActionListener{
  JButton btnAdd= new JButton("Add");
   JButton btnSearch2= new JButton("Search");
   TextField txtWord= new TextField();       
          TextField txtMeaning= new TextField();
            TextField txtsynonym= new TextField();
             JTextArea txtArea2= new JTextArea();
        TextField txtSearch2= new TextField();
   Tree root= new Tree();
    public dictionaryr() {
        initComponents();
        root.insert("chat", "texting someone", "conversation");
root.insert("intent", "purpose", "enrapt");

root.insert("spirit", "the prevailing or typical quality", "ethos");

root.insert("daud", "name of person", "khan");

root.insert("ahmad", "name of person", "baloch");

root.insert("combine", "unite for a common purpose", "join");
root.insert("adnan", "name of person ", " khattak");



    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jPanel1 = new javax.swing.JPanel();
        myPanel = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        btnInsert = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Merriam-Webster Since 1600");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        myPanel.setBackground(new java.awt.Color(204, 153, 255));

        txtSearch.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        btnSearch.setBackground(new java.awt.Color(255, 255, 255));
        btnSearch.setForeground(new java.awt.Color(204, 153, 255));
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        txtArea.setEditable(false);
        txtArea.setColumns(20);
        txtArea.setRows(5);
        txtArea.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Your Searching Results", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        jScrollPane1.setViewportView(txtArea);

        javax.swing.GroupLayout myPanelLayout = new javax.swing.GroupLayout(myPanel);
        myPanel.setLayout(myPanelLayout);
        myPanelLayout.setHorizontalGroup(
            myPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(myPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(myPanelLayout.createSequentialGroup()
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
        );
        myPanelLayout.setVerticalGroup(
            myPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(myPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearch)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnInsert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Insert.png"))); // NOI18N
        btnInsert.setText("Insert New Vocabulary");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Back.png"))); // NOI18N
        btnBack.setText("Go Back");
        btnBack.setEnabled(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnInsert)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(20, 20, 20))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(myPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(myPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
       myPanel.removeAll();
     
       myPanel.setBackground(new Color(255, 255, 255));
         btnBack.setEnabled(true);
         JPanel uperPanel= new JPanel();
         uperPanel.setSize(300, 200);
         uperPanel.setLocation(60, 70);
         uperPanel.setBackground(new Color(255, 255, 102, 120));
         JLabel Title = new JLabel("New Vocabulary");
         Title.setSize(130, 30);
         Title.setLocation(100, 10);
         Title.setForeground(Color.MAGENTA);
         JLabel word= new JLabel("Word");
          word.setSize(90, 30);
         word.setLocation(20, 50);
         word.setForeground(Color.MAGENTA);
          JLabel Meaning= new JLabel("Meaning");
          Meaning.setSize(90, 30);
         Meaning.setLocation(20, 80);
         Meaning.setForeground(Color.MAGENTA);
         JLabel synonym= new JLabel("Synonym");
          synonym.setSize(120, 30);
         synonym.setLocation(20, 110);
         synonym.setForeground(Color.MAGENTA);
         
         
         
          txtWord.setSize(110, 20);
         txtWord.setLocation(140, 50);

          txtMeaning.setSize(110, 20);
         txtMeaning.setLocation(140, 80);
         
       
          txtsynonym.setSize(110, 20);
         txtsynonym.setLocation(140, 110);
         
       
         btnAdd.setSize(70, 30);
         btnAdd.setLocation(175, 145);
         
         myPanel.add(uperPanel);
         uperPanel.add(Title);
         uperPanel.add(word);
          uperPanel.add(Meaning);
          uperPanel.add(synonym);
          uperPanel.add(txtWord);
          uperPanel.add(txtMeaning);
          uperPanel.add(txtsynonym);
          uperPanel.add(btnAdd);
          btnInsert.setEnabled(false);
          btnAdd.addActionListener(this);
    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        myPanel.removeAll();
        myPanel.repaint();
        myPanel.setBackground(new Color(204, 153, 255));
       
        txtSearch2.setFont(new java.awt.Font("Times New Roman", 1, 14));
        txtSearch2.setSize(238, 29);
        txtSearch2.setLocation(26, 23);
       
         btnSearch2.setBackground(new java.awt.Color(255, 255, 255));
        btnSearch2.setForeground(new java.awt.Color(204, 153, 255));
        btnSearch2.setSize(120, 27);
        btnSearch2.setLocation(284, 23);
           btnSearch2.addActionListener(this);
        txtArea2.setSize(406, 267);
        txtArea2.setLocation(5, 65);
        txtArea2.setColumns(20);
        txtArea2.setRows(5);
        txtArea2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Your Searching Results", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        txtArea2.setEditable(false);
        
        myPanel.add(txtSearch2);
        myPanel.add(btnSearch2);
        myPanel.add(txtArea2);
        btnInsert.setEnabled(true);
        btnBack.setEnabled(false);
     
        
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
       String Word= txtSearch.getText();
       Word=root.find(Word);
       txtArea.setText(Word);
    }//GEN-LAST:event_btnSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dictionary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dictionary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dictionary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dictionary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dictionary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnSearch;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel myPanel;
    private javax.swing.JTextArea txtArea;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent ae) 
    {
        if(ae.getSource()==btnSearch2)
        {
           String Word= root.find(txtSearch2.getText());
           JOptionPane.showMessageDialog(null,  Word);
          //txtArea2.append(Word);
        }
        else if(ae.getSource()==btnAdd)
        {
            if(!(txtWord.getText().equals("")&&txtMeaning.getText().equals("")&&txtsynonym.getText().equals("")))
            {
            String Word=txtWord.getText();
            String Meaning=txtMeaning.getText();
            String Synonym=txtsynonym.getText();
            root.insert(Word, Meaning, Synonym);
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Plaese Fill the Fields");
            }
            
        }
    }
}

